### ISSUE TITLE
Peer to peer code reviews

### ISSUE THREAD

**Issue by altontonn** [altontonn/portfolio#3]

**Comment by suzi216** [comment]
In general, the code and website look good, but I would suggest structuring your code a bit more clearly.

**Comment by muskan2532150** [comment]
Instead of using empty div tag we can add  image  to the container using background-image property

**Comment by aceDavon** [comment]
Great work, clean interface. I'd suggest you make your styles a bit in line with the modern way of writing styling, that is using backgrounds for containers and adjusting necessary images than using empty div tags to hold images.
